"""TPM 2.0 quote (TPMS_ATTEST) parsing and the TPM provider.

Parses the ``TPMS_ATTEST`` structure a TPM produces for a quote: the magic value
that proves the structure was generated by a TPM, the attest type, the qualifying
data (the verifier's nonce, carried in ``extraData``), and the PCR digest that
serves as the platform measurement. Verification lives in
:mod:`ca2a_verify.tpm`.

Unlike AMD SEV-SNP and Intel TDX, TPM attestation keys chain to per-vendor EK
roots rather than one published root, so there is no single real root to
validate against. The verifier is exercised against synthetic self-consistent
vectors, and a production deployment supplies its own trusted vendor roots.
Producing a quote requires a real TPM, so :meth:`TpmProvider.attest` fails closed.
"""

from __future__ import annotations

from dataclasses import dataclass

from ca2a_runtime.errors import AttestationFailed, AttestationUnsupported
from ca2a_runtime.tee.base import AttestationReport, BaseProvider

TPM_GENERATED_VALUE = 0xFF544347
TPM_ST_ATTEST_QUOTE = 0x8018
CLOCK_INFO_LEN = 17
FIRMWARE_VERSION_LEN = 8

TPM_DEVICES = ("/dev/tpmrm0", "/dev/tpm0")


def _read_u16(buf: bytes, pos: int) -> tuple[int, int]:
    if pos + 2 > len(buf):
        raise AttestationFailed("TPM quote truncated reading a 16-bit field")
    return int.from_bytes(buf[pos : pos + 2], "big"), pos + 2


def _read_2b(buf: bytes, pos: int) -> tuple[bytes, int]:
    size, pos = _read_u16(buf, pos)
    if pos + size > len(buf):
        raise AttestationFailed("TPM quote truncated reading a sized buffer")
    return buf[pos : pos + size], pos + size


@dataclass(frozen=True)
class TpmQuote:
    """The parsed subset of a TPM 2.0 quote (TPMS_ATTEST) cA2A appraises."""

    magic: int
    attest_type: int
    qualifying_data: bytes  # extraData: the verifier's nonce
    pcr_digest: bytes  # the platform measurement
    raw: bytes

    @classmethod
    def parse(cls, blob: bytes) -> TpmQuote:
        if len(blob) < 6:
            raise AttestationFailed("TPM quote too short")
        magic = int.from_bytes(blob[0:4], "big")
        attest_type, pos = _read_u16(blob, 4)
        _qualified_signer, pos = _read_2b(blob, pos)  # TPM2B_NAME
        qualifying_data, pos = _read_2b(blob, pos)  # extraData / nonce
        pos += CLOCK_INFO_LEN + FIRMWARE_VERSION_LEN
        # TPML_PCR_SELECTION
        if pos + 4 > len(blob):
            raise AttestationFailed("TPM quote truncated reading PCR selection count")
        count = int.from_bytes(blob[pos : pos + 4], "big")
        pos += 4
        for _ in range(count):
            if pos + 3 > len(blob):
                raise AttestationFailed("TPM quote truncated reading a PCR selection")
            size_of_select = blob[pos + 2]
            pos += 3 + size_of_select
        pcr_digest, pos = _read_2b(blob, pos)
        return cls(
            magic=magic,
            attest_type=attest_type,
            qualifying_data=qualifying_data,
            pcr_digest=pcr_digest,
            raw=bytes(blob),
        )


class TpmProvider(BaseProvider):
    """TPM 2.0 provider. Quote generation requires a real TPM."""

    platform = "tpm"

    @classmethod
    def detect(cls) -> bool:
        import os

        return any(os.path.exists(dev) for dev in TPM_DEVICES)

    def attest(self, public_key: str, nonce: str) -> AttestationReport:
        raise AttestationUnsupported(
            "TPM quote generation requires a real TPM",
            detail="no TPM device present; run on a host with a TPM 2.0 / vTPM",
        )
